#
# Example Config
#

generatedPath: ./generatedTest
generatedFiles:
  - template: kitty
    outputPath: ./kitty/kittyTheme.conf
  - template: css
    outputPath: theme.css
  - template: rofi
    outputPath: rofi-colors.rasi
  - template: waybar
    outputPath: waybar-colors.css
  - template: hyprland
    outputPath: hypr-colors.conf

debug: false
