#
# Example Config
#

generatedPath: ./generatedTest
generatedFiles:
  - template: kitty
    outputPath: ./kitty/kittyTheme.conf
  - template: css
    outputPath: theme.css
  - template: rofi
    outputPath: rofi-colors.rasi
debug: false
